# Project name
name: myapp

# Service definitions
services:
  # DB(MySQL) service
  db:
    image: mysql:latest
    container_name: wp_mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: wp_db
      MYSQL_USER: wp_user
      MYSQL_PASSWORD: wp_password
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - my_network
  # WordPress service
  wordpress:
    build: ./wordpress
    container_name: wordpress-app
    restart: always
    depends_on:
      - db
    env_file: ./wordpress/wordpress.env
    # ports:
    #   - "8081:80"
    expose:
      - 9000
    volumes:
      - wordpress_data:/var/www/html
    networks:
      - my_network
  # Nginx service
  nginx:
    image: nginx:latest
    ports:
      - "8081:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - wordpress_data:/var/www/html
      - ./nginx/log:/var/log/nginx
    depends_on:
      - wordpress
    networks:
      - my_network

# Docker volume definitions
volumes:
  db_data:
  wordpress_data:

# Docker networks
networks:
  my_network:
